name: Run reproducer on each commit
on: push
jobs:
  gradle:
    container:
      image: ubuntu:21.10
      options: --cap-add CAP_NET_ADMIN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: help --info
    - name: Add tools
      run: |
        apt update
        apt install -y iproute2 curl
    - name: Info
      run: |
        echo Link
        ip link show
        echo Addr
        ip addr show
    - name: Check for gradle cache
      run: ls -lh ~/.gradle/
    - name: Check for gradle source in cache
      run: find ~/.gradle/ -iname "gradle-*-src.zip"
    - name: Fetch dependencies and build
      run: ./gradlew :downloadDependencies
    - name: Shut down networking
      run: |
        echo "Bring down"
        ip link set dev eth0 down
        echo Link
        ip link show
    - name: Check for gradle source in cache (after network disconnect)
      run: find ~/.gradle/ -iname "gradle-*-src.zip"
    - name: Check that curl installed
      run: curl -V
    - name: Check that services.gradle.org unreachable
      run: /bin/bash -c "! curl https://services.gradle.org"
    - name: Run problematic step
      run: ./gradlew :testKotlinModel
