name: Run reproducer on each commit
on: push
jobs:
  gradle:
    container:
      image: ubuntu:21.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: help --info
    - name: Unshare Info
      run: unshare --help
    - name: Unshare Version
      run: unshare -V
    - name: Simulate failure
      run: exec unshare --net --ipc -c /bin/bash -c "ip link set up lo; /bin/bash -c env"
