name: Run reproducer on each commit
on: push
jobs:
  gradle:
    container:
      image: ubuntu:21.10
      options: --cap-add CAP_NET_ADMIN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: help --info
    - name: Add IP tool
      run: |
        apt update
        apt install -y iproute2
    - name: Info
      run: |
        echo Link
        ip link show
        echo Addr
        ip addr show
        echo "Bring down"
        ip link set dev eth0 down
        echo Link
        ip link show
    - name: Check that services.gradle.org unreachable
      run: curl https://services.gradle.org && exit 1
